server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost/test-avatar?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.hbm2ddl.auto: update
      hibernate.show_sql: false
      hibernate.format_sql: false


#URL_SWAGGER: http://localhost:8080/swagger-ui/index.html
#OpenApi
open_api:
  tittle: PRUEBA AVATAR
  description: API Gestion de inventario
  contact:
    name: Jesus Cangalaya
    email: jesuscangalaya1@gmail.com
  servers:
    local:
      url: http://localhost:8080
      description: Local Environment
    production:
      url: https://Avatar.com
      description: Productive Environment


